// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function DeleteCard(arg1:string,arg2:main.Dialog):Promise<number>;

export function ExportCards(arg1:Array<string>,arg2:string):Promise<number>;

export function GetCard(arg1:string):Promise<backend.Card>;

export function GetCards():Promise<backend.Index>;

export function GetErrors(arg1:string):Promise<backend.CardErrors>;

export function NewCard(arg1:backend.CardData):Promise<number>;

export function ReadSettings():Promise<backend.Settings>;

export function SaveCorrect(arg1:string,arg2:number,arg3:number):Promise<number>;

export function SaveError(arg1:string,arg2:number,arg3:number):Promise<number>;

export function SaveSettings(arg1:backend.Settings):Promise<number>;

export function UpdateCard(arg1:string,arg2:backend.CardData):Promise<number>;
