// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCard(arg1, arg2) {
  return window['go']['main']['App']['DeleteCard'](arg1, arg2);
}

export function ExportCards(arg1, arg2) {
  return window['go']['main']['App']['ExportCards'](arg1, arg2);
}

export function GetCard(arg1) {
  return window['go']['main']['App']['GetCard'](arg1);
}

export function GetCards() {
  return window['go']['main']['App']['GetCards']();
}

export function GetErrors(arg1) {
  return window['go']['main']['App']['GetErrors'](arg1);
}

export function NewCard(arg1) {
  return window['go']['main']['App']['NewCard'](arg1);
}

export function ReadSettings() {
  return window['go']['main']['App']['ReadSettings']();
}

export function SaveCorrect(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCorrect'](arg1, arg2, arg3);
}

export function SaveError(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveError'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function UpdateCard(arg1, arg2) {
  return window['go']['main']['App']['UpdateCard'](arg1, arg2);
}
